[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $projectRoot ".env"

Push-Location $projectRoot
try {
  $ErrorActionPreference = "Continue"
  $statusOutput = & npx supabase status -o json 2>$null | Out-String
  $statusExitCode = $LASTEXITCODE
  $ErrorActionPreference = "Stop"

  if ($statusExitCode -ne 0) {
    throw "Local Supabase is not running. Start Docker Desktop, then run npm run supabase:start."
  }

  $jsonStart = $statusOutput.IndexOf("{")
  if ($jsonStart -lt 0) {
    throw "Supabase CLI did not return JSON status output."
  }

  $status = $statusOutput.Substring($jsonStart) | ConvertFrom-Json
  $existing = @{}
  if (Test-Path -LiteralPath $envPath) {
    foreach ($line in Get-Content -LiteralPath $envPath) {
      if ($line -match '^([A-Z0-9_]+)=(.*)$') {
        $existing[$Matches[1]] = $Matches[2]
      }
    }
  }

  $encryptionKey = $existing["DATA_ENCRYPTION_KEY"]
  if ([string]::IsNullOrWhiteSpace($encryptionKey)) {
    $bytes = New-Object byte[] 32
    $random = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $random.GetBytes($bytes) } finally { $random.Dispose() }
    $encryptionKey = [Convert]::ToBase64String($bytes)
  }

  $openAiKey = $existing["OPENAI_API_KEY"]
  if ($null -eq $openAiKey) { $openAiKey = "" }

  $lines = @(
    "# Generated by scripts/sync-local-env.ps1. Never commit this file."
    "NEXT_PUBLIC_SUPABASE_URL=$($status.API_URL)"
    "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$($status.PUBLISHABLE_KEY)"
    "SUPABASE_SERVICE_ROLE_KEY=$($status.SERVICE_ROLE_KEY)"
    "SUPABASE_DB_URL=$($status.DB_URL)"
    "OPENAI_API_KEY=$openAiKey"
    "OPENAI_MODEL=gpt-5.6-terra"
    "DATA_ENCRYPTION_KEY=$encryptionKey"
    "MCP_SERVERS_JSON=[]"
    "SKILL_REGISTRY_ALLOWLIST="
  )

  [System.IO.File]::WriteAllLines($envPath, $lines, [System.Text.UTF8Encoding]::new($false))
  Write-Host "Local Supabase settings synchronized to .env (secret values hidden)."
}
finally {
  Pop-Location
}
